create table budgets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  category_id bigint references categories(id) not null,
  amount numeric not null,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null
);

-- Index for faster lookups by time/category
create index budgets_category_date_idx on budgets (category_id, start_date, end_date);
