-- 1. Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text not null, -- 'Expense' or 'Investment'
  budget_limit numeric default 0,
  icon text
);
-- 2. Transactions Table
create table transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  amount numeric not null,
  payee text,
  description text,
  category text, -- Storing name for simplicity, could be FK
  type text not null -- 'Expense', 'Income', 'InvestmentIn', 'InvestmentOut'
);
-- 3. Investments Table
create table investments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  category text not null,
  target_amount numeric default 0,
  current_balance numeric default 0
);
-- 4. Insert Default Categories
insert into categories (name, type, budget_limit) values
  ('Groceries', 'Expense', 500),
  ('Rent', 'Expense', 1200),
  ('Entertainment', 'Expense', 200),
  ('Transport', 'Expense', 150),
  ('Utilities', 'Expense', 300),
  ('Salary', 'Income', 0);
-- 5. Insert Default Investments
insert into investments (category, target_amount, current_balance) values
  ('Emergency Fund', 10000, 2000),
  ('Retirement', 100000, 15000),
  ('Crypto', 5000, 500);