-- 1. Create Settings Table (Key-Value Store)
create table settings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  key text unique not null,
  value text,
  value_type text default 'string' -- 'string', 'boolean', 'number', 'json'
);
-- 2. Insert default PIN settings
insert into settings (key, value, value_type) values
  ('pin_hash', null, 'string'),
  ('pin_enabled', 'false', 'boolean'),
  ('last_verified_at', null, 'string');
-- 3. Create function to update timestamp automatically
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;
-- 4. Create trigger to auto-update updated_at
create trigger update_settings_updated_at
  before update on settings
  for each row
  execute function update_updated_at_column();
-- 5. Create index for faster lookups
create index idx_settings_key on settings(key);

-- Add budget duration setting to settings table
-- Run this in Supabase SQL Editor
insert into settings (key, value, value_type) values
  ('budget_duration', 'monthly', 'string')
on conflict (key) do nothing;
-- Possible values: 'weekly', 'monthly', 'yearly'